version: '3.8'

services:
  postgres:
    image: postgres:11
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh

  n8n:
    build:
      context: .               # Current directory as the build context
      dockerfile: Dockerfile   # Specify the Dockerfile to use
    user: "1000:1000"          # Ensure n8n runs as a non-root user
    restart: unless-stopped
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - N8N_HOST=${N8N_HOST}
      - NODE_OPTIONS=--max-old-space-size=512
    ports:
      - ${N8N_PUBLIC_PORT}:5678
    volumes:
      - ./.n8n:/home/node/.n8n  # Workflow and settings storage
      - ./data:/data            # Mount data directory
      - ./env:/env
    links:
      - postgres

  selenium:
    image: selenium/standalone-chrome:latest
    restart: unless-stopped
    ports:
      - "4444:4444"
    volumes:
      - ./selenium:/home/selenium  # Optional folder for Selenium-related storage

volumes:
  postgres_data:
  n8n_data:
